mappings:
- match: telegraf\.(\w+)\.(\w+)\.Avg\.([\w-]+)
  match_type: regex
  name: 'Avg${3}'
  labels:
    client: ${1}
    measurement: ${2}
- match: 'telegraf\.(\w+)\.(\w+)\.([\w-]+)'
  match_type: regex
  name: ${3}
  labels:
    client: ${1}
    measurement: ${2}
